autorizacion_compras/urls.py
from django.contrib import admin
from django.urls import path,include
from modules.login import urls as login_url
from modules.usuario import urls as usuarios_url
from modules.administracion import urls as administracion_urls
from modules.nomencladores import urls as nomencladores_urls
from modules.login.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(login_url),name='login'),
    path('usuario/',include((usuarios_url,'usuario'),namespace='usuario'),name='usuario'),
    path('administracion/',include((administracion_urls,'administracion'),namespace='administracion'),name='administracion'),
    path('nomencladores/',include((nomencladores_urls,'nomencladores'),namespace='nomencladores'),name='nomencladores'),
]

modules/administracion/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import *# asignar_rol, RolUsuarioList, crear_entidad,update_params, get_usuario_rol

urlpatterns = [
    path('asignar_rol/', asignar_rol,name='asigna_rol'),
    path('lista_rol/',RolUsuarioList.as_view(),name='lista_rol'),
    path('crear_entidad/',  EntidadCreate.as_view(),name='crea_entidad'),
    path('parametros/',update_params,name='config_params'),
    path('get_usuario_rol/<int:usuario_id>/', get_usuario_rol, name='get_usuario_rol'),
    #path('flujo_aprobacion/',)
    path('asigna_usuario_entidad/<int:codigo_entidad>',asigna_usuario_entidad,name="asigna_usuario_entidad"),
    path('lista_entidades/', EntidadList.as_view(),name="lista_entidades"),    
    
]

modules/administracion/models.py
from django.db import models
from django.contrib.auth.models import User
from ..usuario.models import Usuario
from typing import Any
#from django.contrib.postgres.fields import ArrayField


# Create your models here.
class Entidad(models.Model):
    codigo = models.IntegerField()
    nombre = models.CharField(max_length=128)
    #usuarios = models.ForeignKey(Usuario, null=True, blank=True, on_delete=models.CASCADE)  
    usuarios = models.ManyToManyField(Usuario,related_name='usuarios_entidad')
    

class ConfigParametros(models.Model):
    limite_crear_sao = models.IntegerField(blank=True,null=True)
    limite_aprobacion_division = models.IntegerField(blank=True,null=True)
    num_aprob_sao = models.CharField(max_length=50,blank=True,null=True)
    nomenclador_general = models.CharField(max_length=50,blank=True)
    proveedores = models.CharField(max_length=50,blank=True)
    inversiones = models.CharField(max_length=50,blank=True)
    sao = models.CharField(max_length=50,blank=True)
    entidades = models.CharField(max_length=50,blank=True)

    def save(self, *args, **kwargs):  # type: ignore
        """Save object to the database. All other entries, if any, are removed."""
        self.__class__.objects.exclude(id=self.id).delete()
        super().save(*args, **kwargs)
    
    @classmethod
    def load(cls) -> Any:
        """Load the model instance."""
        obj, _ = cls.objects.get_or_create(id=1)
        return obj

class Condicion(models.Model):
    campo = models.CharField(max_length=30)
    comparacion = models.CharField(max_length=30)
    valor = models.CharField(max_length=30)
    siguiente = models.OneToOneField(Usuario,on_delete=models.CASCADE)

class PerfilAprobador(models.Model):
    usuario = models.OneToOneField(Usuario,related_name='usuario_aprobador',on_delete=models.CASCADE)
    sustituto = models.OneToOneField(Usuario,related_name='usuario_sustituto',on_delete=models.CASCADE)
    notificar_a = models.EmailField()
    condicion = models.ForeignKey(Condicion, on_delete=models.CASCADE)


    


     

modules/administracion/forms.py
from django import forms
from ..usuario.models import Usuario
from .models import Entidad, ConfigParametros

class RolUsuarioForm(forms.Form):
    roles = [('1','Solicitante'),('2','Firmante A'),('3','Firmante B'),('4','Aprobador')]
    rol = forms.ChoiceField(widget=forms.RadioSelect(attrs={'name':"rol"}),choices=roles)
    username = forms.ModelChoiceField(queryset=Usuario.objects.all())
    firma = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Firma', 'name':"firma"}))

    class Meta:
        model = Usuario
        fields = [
            'username',
            'rol',
            'firma'
        ] 
        labels = {
            'username': 'Nombre de usuario',
            'rol': 'Rol del usuario',
            'firma': 'Firma',
        }
    
class CreaEntidadForm(forms.ModelForm):
    #nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre', 'name':"nombre"}))
    #codigo = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Código','name':'codigo'}))
    #usuarios = forms.ModelChoiceField(queryset=Usuario.objects.all())

    class Meta:
        model = Entidad
        fields = [
            'nombre',
            'codigo',
            #'usuarios'
        ] 
        labels = {
            'nombre': 'Nombre de entidad',
            'codigo': 'Código de entidad',
            #'usuarios': 'Usuarios',
        }

class AsignarUsuarioEntidadForm(forms.ModelForm):
    usuarios = forms.ModelChoiceField(queryset=Usuario.objects.all())

    class Meta:
        model = Entidad
        fields = [
            #'nombre',
            #'codigo',
            'usuarios'
        ] 
        labels = {
            #'nombre': 'Nombre de entidad',
            #'codigo': 'Código de entidad',
            'usuarios': 'Usuarios',
        }

class ConfigParametrosForm(forms.ModelForm):
    
    class Meta:
        model = ConfigParametros

        fields = [
            'limite_crear_sao',
            'limite_aprobacion_division',
            'num_aprob_sao',
            'nomenclador_general',
            'proveedores',
            'inversiones',
            'sao',
            'entidades',
        ] 
        labels = {
            'limite_crear_sao' : 'Limite para crear SAO(USD)',
            'limite_aprobacion_division': 'Limite Aprobacion División',
            'num_aprob_sao': 'Número de Aprobación SAO(<10000)',
            'nomenclador_general': 'Nomenclador general',
            'proveedores': 'Provedores',
            'inversiones': 'Inversiones',
            'sao': 'SAO',
            'entidades': 'Entidades',
        }

modules/administracion/views.py
from django.shortcuts import render,redirect
from django.views.generic import UpdateView,ListView, CreateView
from ..usuario.models import Usuario
from .models import ConfigParametros, Entidad
from .forms import RolUsuarioForm, CreaEntidadForm,ConfigParametrosForm,AsignarUsuarioEntidadForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse,JsonResponse

def get_usuario_rol(request, usuario_id):
    # Obtener el usuario por su ID
    usuario = Usuario.objects.get(id=usuario_id)

    # Devolver el rol del usuario como respuesta JSON
    return JsonResponse({'rol': usuario.rol})


nombre_rol = {
    '1':'Solicitante',
    '2':'Firmante A',
    '3':'Firmante B',
    '4':'Aprobador',
}

# Create your views here.
class RolUsuarioList(ListView):
    model = Usuario
    template_name = 'administracion/usuario_rol_list.html'

def update_params(request):
    if request.method == 'POST':
        form = ConfigParametrosForm(request.POST)
        config = ConfigParametros.load()
        if form.is_valid():
            config.limite_crear_sao = form.cleaned_data['limite_crear_sao']
            config.limite_aprobacion_division = form.cleaned_data['limite_aprobacion_division']
            config.num_aprob_sao = form.cleaned_data['num_aprob_sao']
            config.nomenclador_general = form.cleaned_data['nomenclador_general']
            config.proveedores = form.cleaned_data['proveedores']
            config.inversiones = form.cleaned_data['inversiones']
            config.sao = form.cleaned_data['sao']
            config.entidades = form.cleaned_data['entidades']
            config.save()
            return render(request,'administracion/config_params.html',{'config':config,'form':form})
    else:
        config = ConfigParametros.load()
        form = ConfigParametrosForm() 
    return render(request,'administracion/config_params.html',{'config':config,'form':form})

def asignar_rol(request):
    if request.method == 'POST':
        form = RolUsuarioForm(request.POST)
        if form.is_valid():
            seleccion = form.cleaned_data['username']
            registro = Usuario.objects.get(username=seleccion.username)
            id_rol = form.cleaned_data['rol']
            rol = nombre_rol[id_rol]
            firma = form.cleaned_data['firma']
            #Actualizo
            registro.rol = rol
            registro.firma = make_password(firma)
            registro.save()
            return redirect('administracion:lista_rol')
    else:
        form = RolUsuarioForm()
    return render(request, 'administracion/asignar_rol.html', {'form': form})

def crear_entidad(request):
    if request.method == 'POST':
        form = CreaEntidadForm(request.POST)
        if form.is_valid():
           form.save()
           return redirect('administracion:crea_entidad')
    else:
        form = CreaEntidadForm()
    return render(request, 'administracion/crear_entidad_copy.html', {'form': form})

class EntidadCreate(CreateView):
    model = Entidad
    form_class = CreaEntidadForm
    template_name = 'administracion/crear_entidad_copy.html'
    success_url = reverse_lazy('administracion:asigna_usuario_entidad')

    def get_success_url(self):
        #nombre = self.form_class.cleaned_data['nombre']
        #print('Nombre   ',nombre)
        codigo = self.object.codigo
        print('Codigo   ',codigo, type(codigo))
        return reverse_lazy('administracion:asigna_usuario_entidad',
                            kwargs={'codigo_entidad':codigo})
    
def asigna_usuario_entidad(request,codigo_entidad):
    form = AsignarUsuarioEntidadForm()
    if request.method == 'POST':
        seleccion = request.POST.get('username')
        if seleccion:
            entidad = Entidad.objects.get(codigo=codigo_entidad)
            usuario = Usuario.objects.get(username=seleccion)

            #Actualizo
            entidad.usuarios.add(usuario)
            entidad.save()

            lista_usuarios = entidad.usuarios.all()
            return render(request, 'administracion/asignar_usuario_entidad.html',
                              {'form':form,'lista_usuarios':lista_usuarios})
        
    entidad = Entidad.objects.get(codigo=codigo_entidad)

    lista_usuarios = entidad.usuarios.all()
    return render(request, 'administracion/asignar_usuario_entidad.html',
                    {'form':form,'lista_usuarios':lista_usuarios})
    #return render(request, 'administracion/asignar_usuario_entidad.html', {'form': form})

class EntidadList(ListView):
    model = Entidad
    template_name = 'administracion/lista_entidades.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Realiza la consulta para obtener los elementos de EntidadUsuario donde entidad es igual a 6
        entidades = Entidad.objects.all()
        entidad_usuario = {}
        for entidad in entidades:
            entidad_usuario[entidad.id] = entidad.usuarios.all()# .objects.filter(id=entidad.id)
            print(entidad_usuario[entidad.id])
        # Pasa los resultados al contexto
        context['entidad_usuario'] = entidad_usuario
        return context

def flujo_aprobacion():
    return

templates/administracion/asignar_rol.html
{% extends "base/base.html" %}

{% block wrapper %}

<div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
    <!--begin::Container-->
    <div class="container">
                <div class="card card-custom">
                <div class="card-header">
                    <h1 class="card-title">
                    Asignar Rol
                    </h1>
                </div>
                <!--begin::Form-->
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <!-- Usuario  -->
                        <div class="form-group">
                            <div class="input-group">
                                <select class="custom-select form-control" name="username">
                                    <option value selected>Selecciona el usuario</option>
                                    {% if form.username %}
                                    {% for value,label in form.username.field.choices %}
                                        <option value ="{{value}}">{{label}}</option>
                                    {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>

                        <!-- End Usuario  -->

                        <!-- Radios -->
                        <div class="form-group ">
                            <label class="col-3 col-form-label">Seleccione el {{form.rol.label}}</label>
                            <div class="col-9 col-form-label">
                                <div class="radio-list">
                                    {% for value,label in form.rol.field.choices %}
                                    <label class="radio">
                                        <input type="radio"  name="rol" value ="{{value}}"/>
                                        <span></span>
                                        {{label}}
                                    </label>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- End Radios -->

                        <!-- Firma -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text" style="display: none;" id="span_firma">{{form.firma.label}}</span></div>
                                <input type="text" class="form-control" placeholder="Firma" name="firma" id="firma" style="display: none;"/>

                            </div>
                        </div>
                        <!-- End Firma -->

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}:</strong> {{ error }}
                            {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </form>
                <!--end::Form-->
                </div>
            
        
    </div>
</div> 
{% endblock %}

templates/administracion/asignar_usuario_entidad.html
{% extends "base/lista_base.html" %}

{% block subheader %}
{% endblock %}

{% block title_table %}  
Asignar usuarios a entidad 
{% endblock %}

{% block form %}
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                
                <!--begin::Form-->
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <!-- Usuarios  -->
                        <div class="form-group">
                            <div class="input-group">
                                <select class="custom-select form-control" name="username">
                                    <option value selected>Selecciona el usuario</option>
                                    {% if form.usuarios %}
                                    {% for value,label in form.usuarios.field.choices %}
                                        <option value ="{{label}}">{{label}}</option>
                                    {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>
                    <button type="submit" name ="anadir_usuario"  class="btn btn-primary mr-2" style="margin-left:10px">Añadir</button>
                
                        <div class="card-body">
                            <!--begin: Datatable-->
                            <table class="table table-bordered table-checkable" >
                                <thead>
                                    <tr>
                                        <th>Nombre de usuario</th>
                                        <th>Rol</th>
                                    </tr>
                                </thead>
                                <body id="tabla_usuarios_entidad">
                                    {% if lista_usuarios %}
                                        {% for usuario in lista_usuarios %}
                                            <tr>
                                                <td>{{usuario.username}}</td>
                                                <td>{{usuario.rol}}</td>
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </body>
                            </table>
                            <!--end: Datatable-->
                        </div>
                        <!-- End Usuarios  -->

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'administracion:lista_entidades' %}" class="btn btn-primary mr-2">Continuar</a>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}:</strong> {{ error }}
                            {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </form>
                <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/administracion/config_params.html
{% extends "base/base.html" %}

{% block wrapper %}

<div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
    <!--begin::Container-->
    <div class="container">
                <div class="card card-custom">
                <div class="card-header">
                    <h1 class="card-title">
                    Configuración de parámetros
                    </h1>
                </div>
                <!--begin::Form-->
                <form class="form " method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <h6>Límites</h6>
                        <hr>
                        <!-- Limite para crear SAO(USD) -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.limite_crear_sao.label}}</span></div>
                                <input type="text" class="form-control" placeholder="{{form.limite_crear_sao.label}}" name="limite_crear_sao" value ={{config.limite_crear_sao}} />
                            </div>
                        </div>
                        <!-- End Limite para crear SAO(USD) -->

                        <!-- Limite Aprobacion División -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.limite_aprobacion_division.label}}</span></div>
                                <input type="text" class="form-control" placeholder="{{form.limite_aprobacion_division.label}}" name="limite_aprobacion_division" value ={{config.limite_aprobacion_division}} />
                            </div>
                        </div>
                        <!-- End Limite Aprobacion División -->

                        <!-- Número de Aprobación SAO(<10000) -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.num_aprob_sao.label}}</span></div>
                                <input type="text" class="form-control" placeholder="{{form.num_aprob_sao.label}}" name="num_aprob_sao" value ={{config.num_aprob_sao}} />
                            </div>
                        </div>
                        <!-- Número de Aprobación SAO(<10000) -->

                        <h6>Enlaces a otros sistemas</h6>
                        <hr>
                        <!-- Nomenclador general -->
                            <div class="form-group">
                                <div class="input-group">
                                <div class="input-group-prepend"><span class="input-group-text">{{form.nomenclador_general.label}}</span></div>
                                    <input type="text" class="form-control" placeholder="{{form.nomenclador_general.label}}" name="nomenclador_general" value ={{config.nomenclador_general}} />
                                </div>
                            </div>
                        <!-- Nomenclador general -->

                        <!-- Provedores -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.proveedores.label}}</span></div>
                                <input type="text" class="form-control" placeholder="{{form.proveedores.label}}" name="proveedores" value ={{config.proveedores}} />
                            </div>
                        </div>
                    <!-- Provedores -->
                    
                    <!-- Inversiones -->
                    <div class="form-group">
                        <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">{{form.inversiones.label}}</span></div>
                            <input type="text" class="form-control" placeholder="{{form.inversiones.label}}" name="inversiones" value ={{config.inversiones}} />
                        </div>
                    </div>
                    <!-- Inversiones -->

                    <!-- SAO -->
                    <div class="form-group">
                        <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">{{form.sao.label}}</span></div>
                            <input type="text" class="form-control" placeholder="{{form.sao.label}}" name="sao" value ={{config.sao}} />
                        </div>
                    </div>
                    <!-- SAO -->

                    <!-- Entidades -->
                    <div class="form-group">
                        <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">{{form.entidades.label}}</span></div>
                            <input type="text" class="form-control" placeholder="{{form.entidades.label}}" name="entidades" value ={{config.entidades}} />
                        </div>
                    </div>
                    <!-- Entidades -->


                        
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}:</strong> {{ error }}
                            {% endfor %}
                        {% endfor %}
                        </div>
                    {% endif %}
                </form>
                <!--end::Form-->
                </div>
            
        
    </div>
</div>
{% endblock %}

templates/administracion/crear_entidad.html
{% extends "base/base.html" %}

{% block wrapper %}
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-custom">
                <div class="card-header">
                    <h1 class="card-title">
                    Crear Entidad
                    </h1>
                </div>
                <!--begin::Form-->
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <!-- Nombre -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.nombre.label}}</span></div>
                                <input type="text" class="form-control" placeholder="Nombre de la entidad" name="nombre"/>
                            </div>
                        </div>
                        <!-- End Nombre -->

                        <!-- Codigo -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.codigo.label}}</span></div>
                                <input type="text" class="form-control" placeholder="Código de la entidad" name="codigo"/>
                            </div>
                        </div>
                        <!-- End Codigo -->

                        <!-- Usuarios  -->
                        <div class="form-group">
                            <div class="input-group">
                                <select class="custom-select form-control" name="usuarios">
                                    <option value selected>Selecciona el usuario</option>
                                    {% if form.usuarios %}
                                    {% for value,label in form.usuarios.field.choices %}
                                        <option value ="{{value}}">{{label}}</option>
                                    {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>
                        <!-- End Usuarios  -->

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}:</strong> {{ error }}
                            {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </form>
                <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/administracion/crear_entidad_copy.html
{% extends "base/lista_base.html" %}

{% block subheader %}
{% endblock %}

{% block title_table %}  
Crear Entidad
{% endblock %}

{% block form %}
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                
                <!--begin::Form-->
                <form class="form" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <!-- Nombre -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.nombre.label}}</span></div>
                                <input type="text" class="form-control" placeholder="Nombre de la entidad" name="nombre"/>
                            </div>
                        </div>
                        <!-- End Nombre -->

                        <!-- Codigo -->
                        <div class="form-group">
                            <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">{{form.codigo.label}}</span></div>
                                <input type="text" class="form-control" placeholder="Código de la entidad" name="codigo"/>
                            </div>
                        </div>
                        <!-- End Codigo -->

                       

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <strong>{{ field.label }}:</strong> {{ error }}
                            {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </form>
                <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/administracion/lista_entidades.html
{% extends "base/lista_base.html" %}
{% load static %}


{% block title_page %}Entidades {% endblock %}

{% block title_table %} Entidades {% endblock %}
{% block subtitle_table %}Lista de Entidades del sistema {% endblock %}

{% block head_table %}
<tr>
    <th>Nombre de Entidad</th>
    <th>Codigo</th>
</tr>
{% endblock %}

{% block content_table %}

{% if object_list %}
{% for entidad in object_list %}
    <tr>
        <td>{{ entidad.nombre }}</td>
        <td>{{ entidad.codigo }}</td>
    </tr>
    {% for key,usuarios in entidad_usuario.items %}
        {% if key == entidad.id%}
            {% for usuario in usuarios %}
                <tr>
                    <td>{{usuario.username}}</td></tr>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endfor %}
{% endif %} 

{% endblock %}